version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2
  maven: circleci/maven@0.0.12

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:latest'
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run: mvn clean install
      - run: mvn test
      - run: bash <(curl -s https://codecov.io/bash) -v
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target
      - codecov/upload:
          file: target/surefire-reports
